### ISSUE TITLE
Setting different user in templated exporters

### ISSUE THREAD

**Issue by karlism** [lest/prometheus-rpm#214]
I've tried to switch `keepalived_exporter` to root user (as it requires to be run as `root` since it needs to send `SIGUSR1` to `keepalived` process, which runs as `root` on CentOS).

After adding `user` and `group` paramters to template as following I discovered couple of issues:
```yaml
  keepalived_exporter:
    build_steps:
      <<: *default_build_steps
    context:
      <<: *default_context
      static:
        <<: *default_static_context
        version: 0.4.0
        license: ASL 2.0
        user: root
        group: root
        release: 2
        URL: https://github.com/gen2brain/keepalived_exporter
        package: '%{name}-%{version}-amd64'
        summary: Prometheus exporter for Keepalived metrics
        description: Export Keepalived service metrics to Prometheus.
      dynamic:
        <<: *default_dynamic_context
        tarball: '{{URL}}/releases/download/%{version}/{{package}}.tar.gz'
```

Package cannot be installed as it conflicts with other packages:
```
Transaction check error:
  file /var/lib/prometheus from install of keepalived_exporter-0.4.0-2.el7.x86_64 conflicts with file from package node_exporter-0.18.1-1.el7.centos.x86_64
  file /var/lib/prometheus from install of keepalived_exporter-0.4.0-2.el7.x86_64 conflicts with file from package blackbox_exporter-0.16.0-1.el7.centos.x86_64
  file /var/lib/prometheus from install of keepalived_exporter-0.4.0-2.el7.x86_64 conflicts with file from package snmp_exporter-0.17.0-2.el7.x86_64
```

It attempts to create `/var/lib/prometheus` directory with user and group `root`, which conflicts with other exporters:
```
$ cat keepalived_exporter/autogen_keepalived_exporter.spec | grep -e "%define" -e "%dir"
%define debug_package %{nil}
%define user root
%define group root
%dir %attr(755, %{user}, %{group}) %{_sharedstatedir}/prometheus
```

Additionally to that package still attempts to create `prometheus` user and group, despite the fact that they are not really necessary in this scenario:
```
$ cat keepalived_exporter/autogen_keepalived_exporter.spec | grep -A4 "%pre$"
%pre
getent group prometheus >/dev/null || groupadd -r prometheus
getent passwd prometheus >/dev/null || \
  useradd -r -g prometheus -d %{_sharedstatedir}/prometheus -s /sbin/nologin \
          -c "Prometheus services" prometheus
```
